In [1]:
import gym
import numpy as np

In [2]:
env = gym.make('FrozenLake-v0')

[2017-02-01 21:26:58,321] Making new env: FrozenLake-v0


In [19]:
Q = np.zeros([env.observation_space.n,env.action_space.n])

In [24]:
env.action_space.sample()

1

In [39]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset() ## State
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1))) ## Action
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [40]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.373


In [35]:
print Q

[[  7.86601190e-01   6.59705057e-03   7.80627359e-03   1.71778698e-02]
 [  1.71663409e-04   8.85844237e-04   5.20912130e-04   4.26501381e-01]
 [  2.93704463e-01   2.36657122e-03   4.22825060e-03   3.03831653e-03]
 [  2.69566731e-03   1.06516514e-05   4.61872749e-04   3.12930864e-03]
 [  7.83077942e-01   4.30215709e-04   1.23238311e-03   1.89029825e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  6.17102264e-07   5.71567628e-09   4.37007387e-02   6.97532175e-07]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.11494992e-04   1.34314017e-03   5.78829233e-05   5.06173026e-01]
 [  4.74193575e-03   7.51877466e-01   1.50011945e-03   3.13557471e-03]
 [  9.48008166e-01   4.92500127e-04   1.60374950e-04   4.97426807e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   5.73720361e-04   9.28050548e-01   0.00000000e+00]
 [  0.

['P',
 '__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_close',
 '_closed',
 '_configure',
 '_configured',
 '_env_closer_id',
 '_owns_render',
 '_render',
 '_reset',
 '_seed',
 '_step',
 '_unwrapped',
 'action_space',
 'close',
 'configure',
 'desc',
 'isd',
 'lastaction',
 'metadata',
 'monitor',
 'nA',
 'nS',
 'ncol',
 'np_random',
 'nrow',
 'observation_space',
 'render',
 'reset',
 'reward_range',
 's',
 'seed',
 'spec',
 'step',
 'unwrapped']